/***************************************************************************//**
* \file MAGIC_WAND_ifx_model_float.h
*
* \brief
* Autogenerated with ml-coretools, this file contains MAGIC_WAND model data.
* Date: 2023-01-17 16:43:47.063166
*******************************************************************************
* \copyright
* Copyright 2023, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef MAGIC_WAND_IFX_MODEL_FLOAT_H
#define MAGIC_WAND_IFX_MODEL_FLOAT_H

#include <stdint.h>


extern const uint8_t MAGIC_WAND_model_prms_bin[];
#define MAGIC_WAND_MODEL_PRMS_BIN_LEN 456

#ifdef CY_ML_MODEL_MEM
extern const uint8_t MAGIC_WAND_model_bin[];
#else
extern uint8_t MAGIC_WAND_model_bin[];
#endif // CY_ML_MODEL_MEM
#define MAGIC_WAND_MODEL_BIN_LEN 21900


#define MAGIC_WAND_MODEL_NUM_OF_LAYERS        8
#define MAGIC_WAND_MODEL_NUM_OF_RESIDUAL_CONN 0
#define MAGIC_WAND_MODEL_INPUT_DATA_SIZE      768
#define MAGIC_WAND_MODEL_OUTPUT_DATA_SIZE     4


#define MAGIC_WAND_MODEL_SIZE_OF_STATE_OUT   0
#define MAGIC_WAND_MODEL_SCRATCH_MEM_SIZE    59904


#endif // MAGIC_WAND_IFX_MODEL_FLOAT_H
