/***************************************************************************//**
* \file MAGIC_WAND_tflm_model_float.h
*
* \brief
* Autogenerated with ml-coretools, this file contains MAGIC_WAND model data.
* Date: 2023-01-17 16:44:00.646431
*******************************************************************************
* \copyright
* Copyright 2023, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef MAGIC_WAND_TFLM_MODEL_FLOAT_H
#define MAGIC_WAND_TFLM_MODEL_FLOAT_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t MAGIC_WAND_model_bin[];
#else
extern uint8_t MAGIC_WAND_model_bin[];
#endif // CY_ML_MODEL_MEM
#define MAGIC_WAND_MODEL_BIN_LEN (25244u)
#define MAGIC_WAND_ARENA_SIZE (60189u)

#endif // MAGIC_WAND_TFLM_MODEL_FLOAT_H

